package repository

import "database/sql"

type CustomerModel struct {
	ID                      sql.NullInt64
	UUIDKey                 sql.NullString
	IsPrincipal             sql.NullBool
	PrincipalID             sql.NullInt64
	IsParent                sql.NullBool
	ParentCustomerID        sql.NullInt64
	ParentCustomerName      sql.NullString
	MDBParentCustomerID     sql.NullInt64
	MDBCompanyProfileID     sql.NullInt64
	ClientType              sql.NullString
	Npwp                    sql.NullString
	MDBCompanyTitleID       sql.NullInt64
	CompanyTitle            sql.NullString
	CustomerName            sql.NullString
	Address                 sql.NullString
	Address2                sql.NullString
	Address3                sql.NullString
	Hamlet                  sql.NullString
	Neighbourhood           sql.NullString
	CountryID               sql.NullInt64
	ProvinceID              sql.NullInt64
	ProvinceName            sql.NullString
	DistrictID              sql.NullInt64
	DistrictName            sql.NullString
	SubDistrictID           sql.NullInt64
	SubDistrictName         sql.NullString
	UrbanVillageID          sql.NullInt64
	UrbanVillageName        sql.NullString
	PostalCodeID            sql.NullInt64
	PostalCode              sql.NullString
	Longitude               sql.NullFloat64
	Latitude                sql.NullFloat64
	Phone                   sql.NullString
	AlternativePhone        sql.NullString
	Fax                     sql.NullString
	CompanyEmail            sql.NullString
	AlternativeCompanyEmail sql.NullString
	CustomerSource          sql.NullString
	TaxName                 sql.NullString
	TaxAddress              sql.NullString
	SalesmanID              sql.NullInt64
	SalesmanFirstName       sql.NullString
	SalesmanLastName        sql.NullString
	RefCustomerID           sql.NullInt64
	RefCustomerName         sql.NullString
	DistributorOF           sql.NullString
	CustomerGroupID         sql.NullInt64
	CustomerGroupName       sql.NullString
	CustomerCategoryID      sql.NullInt64
	CustomerCategoryName    sql.NullString
	Status                  sql.NullString
	CustomerContactStr      sql.NullString
	CustomerContact         []CustomerContactModel
	IsUsed                  sql.NullBool
	InstallationDate        sql.NullTime
	ProductValidFrom        sql.NullTime
	ProductValidThru        sql.NullTime
	UniqueID1               sql.NullString
	UniqueID2               sql.NullString
	ActivationDate          sql.NullTime
	CreatedBy               sql.NullInt64
	CreatedAt               sql.NullTime
	CreatedClient           sql.NullString
	CreatedName             sql.NullString
	UpdatedBy               sql.NullInt64
	UpdatedAt               sql.NullTime
	UpdatedClient           sql.NullString
	UpdatedName             sql.NullString
	Deleted                 sql.NullBool
	ClientID                sql.NullString
	AuthUserID              sql.NullInt64
	LicenseVariantName      sql.NullString
}
