package in

const DataGroupDTOFileName = "DataGroupDTO.go"
const CustomerGroupDTOFileName = "CustomerGroupDTO.go"
const CustomerCategoryDTOFileName = "CustomerCategoryDTO.go"
const ProductGroupDTOFileName = "ProductGroupDTO.go"
const LicenseTypeDTOFileName = "LicenseTypeDTO.go"
const ModuleDTOFileName = "ModuleDTO.go"
const ComponentDTOFileName = "ComponentDTO.go"
const UrbanVillageDTOFileName = "UrbanVillageDTO.go"
const SubDistrictDTOFileName = "SubDistrictDTO.go"
const CustomerDTOFileName = "CustomerDTO.go"
const CustomerContactDTOFileName = "CustomerContactDTO.go"
const PostalCodeDTOFileName = "PostalCodeDTO.go"
const ProductLicenseDTOFilename = "ProductLicenseDTO.go"
const ActivationLicenseDTOFileName = "ActivationLicenseDTO.go"
const ValidationLicenseDTOFileName = "ValidationLicenseDTO.go"
const ActivationUserNexmileDTOFileName = "ActivationUserNexmileDTO.go"
const ValidationNamedUserDTOFilename = "ValidationNamedUserDTOFilename.go"
const RoleDTOFilename = "RoleDTO.go"
const UpdateLicenseHIWDDTOFileName = "ActivationLicenseDTO.go"
const AbstractDTOFileName = "AbstractDTO.go"
const GetListDataDTOFileName = "GetListDataDTO.go"
