package constanta

// ---------------------------------------------- Authentication -------------------------------------------------------
const CodeChallenger = "CODE_CHALLENGER"
const Username = "USERNAME"
const Password = "PASSWORD"
const OldPassword = "OLD_PASSWORD"
const AuthorizationCode = "AUTHORIZATION_CODE"
const CodeVerifier = "CODE_VERIFIER"
const RefreshToken = "REFRESH_TOKEN"

// --------------------------------------------------- Common ----------------------------------------------------------
const BtlAccountID = "BTL_ACCOUNT_ID"
const TableName = "TABLE_NAME"
const PrimaryKey = "PRIMARY_KEY"
const ID = "ID"
const Data = "DATA"
const Name = "NAME"
const IDCard = "ID_CARD"
const AnonymizedName = "ANONYMIZED_NAME"
const Code = "CODE"
const CreatedAt = "CREATED_AT"
const DefaultOrderBy = "default"
const CreatedAtDesc = "created_at DESC"
const UpdatedAt = "UPDATED_AT"
const PhoneCode = "PHONE_CODE"
const Parameter = "PARAMETER"
const ErrorSpecialCharacter = "SPECIAL_CHARACTER_ERROR"
const ErrorWhitelistSpecialCharacter = "SPECIAL_CHARACTER_WHITELIST_ERROR"
const ErrorSpecialCharacterAlphabet = "SPECIAL_CHARACTER_ALPHABET_ERROR"
const ErrorEmptyString = "EMPTY_STRING_ERROR"
const SessionUser = "session.user."
const AllSessionUser = "session.user.*"
const SessionAdmin = "session.admin."

// ---------------------------------------------- Paging List ----------------------------------------------------------
const Page = "PAGE"
const Limit = "LIMIT"
const Filter = "FILTER"
const Search = "SEARCH"
const OrderBy = "ORDER_BY"

// ------------------------------------------------- MenuBundle List ---------------------------------------------------
const Country = "COUNTRY"
const Province = "PROVINCE"
const District = "DISTRICT"
const SubDistrict = "SUB_DISTRICT"
const UrbanVillage = "URBAN_VILLAGE"
const PostalCode = "POSTAL_CODE"
const Island = "ISLAND"
const PersonTitle = "PERSON_TITLE"
const CompanyTitle = "COMPANY_TITLE"
const Bank = "BANK"
const PersonProfile = "PERSON_PROFILE"
const CompanyProfile = "COMPANY_PROFILE"
const GroupOfDistributor = "GROUP_OF_DISTRIBUTOR"
const Principal = "PRINCIPAL"
const VendorChannel = "VENDOR_CHANNEL"
const ContactPerson = "CONTACT_PERSON"
const ProductHistory = "PRODUCT_HISTORY"
const BrandOwner = "BRAND_OWNER"
const ProductCategory = "PRODUCT_CATEGORY"
const ProductGroupHierarchy = "PRODUCT_GROUP_HIERARCHY"
const Product = "PRODUCT"
const ProductBrand = "PRODUCT_BRAND"
const ProductKeyAccount = "PRODUCT_KEY_ACCOUNT"
const ProductKey = "PRODUCT_KEY"
const ProductEncrypt = "PRODUCT_ENCRYPT"

// -------------------------------------------------- ID MenuBundle ----------------------------------------------------
const CountryID = "COUNTRY_ID"
const ProvinceID = "PROVINCE_ID"
const DistrictID = "DISTRICT_ID"
const SubDistrictID = "SUB_DISTRICT_ID"
const UrbanVillageID = "URBAN_VILLAGE_ID"
const PostalCodeID = "POSTAL_CODE_ID"
const IslandID = "ISLAND_ID"
const PersonTitleID = "PERSON_TITLE_ID"
const CompanyTitleID = "COMPANY_TITLE_ID"
const CompanyProfileID = "COMPANY_PROFILE_ID"
const ProductID = "PRODUCT_ID"
const PreviousProductID = "PREVIOUS_PRODUCT_ID"
const BrandOwnerID = "BRAND_OWNER_ID"
const BrandID = "BRAND_ID"
const PrincipalID = "PRINCIPAL_ID"
const ProductBrandID = "PRODUCT_BRAND_ID"
const ProductCategoryID = "PRODUCT_CATEGORY_ID"
const ProductGroupHierarchyID = "PRODUCT_GROUP_HIERARCHY_ID"
const ProductKeyAccountID = "PRODUCT_KEY_ACCOUNT_ID"

// ----------------------------------------------- Role Company Profile ------------------------------------------------
const CompanyProfileRolePrincipal = "PR"
const CompanyProfileRoleDistributor = "DS"
const CompanyProfileRoleVendor = "VR"
const CompanyProfileRoleWholesaler = "WS"
const CompanyProfileRoleOutlet = "OT"
const CompanyProfileRoleGroupOfDistributor = "GDS"
const CompanyProfileRoleBTLAccount = "BTL"
const CompanyProfileRoleTeam = "TM"

const Description = "DESCRIPTION"
const ENDescription = "EN_DESCRIPTION"
const Title = "TITLE"
const Status = "STATUS"
const NPWP = "NPWP"
const MDBNPWP = "MDB_NPWP"
const MDBCompanyProfileID = "MDB_COMPANY_PROFILE_ID"
const NIK = "NIK"
const Address = "ADDRESS"
const Hamlet = "HAMLET"
const Neighbourhood = "NEIGHBOURHOOD"
const Phone = "PHONE"
const PhoneOTP = "PHONE_OTP"
const Fax = "FAX"
const TaxName = "TAX_NAME"
const TaxAddress = "TAX_ADDRESS"
const FaxCode = "FAX_CODE"
const Email = "EMAIL"
const ForgetCode = "FORGET_CODE"
const EmailCode = "EMAIL_CODE"
const PersonProfilePhoto = "PERSON_PROFILE_PHOTO"
const CompanyProfileLogo = "COMPANY_PROFILE_LOGO"
const PrincipalPhoto = "PRINCIPAL_PHOTO"
const ProductPhoto = "PRODUCT_PHOTO"
const AdditionalInfo = "ADDITIONAL_INFO"
const FirstName = "FIRST_NAME"
const LastName = "LAST_NAME"
const Sex = "SEX"
const Address1 = "ADDRESS1"
const Address2 = "ADDRESS2"
const Address3 = "ADDRESS3"
const SexRegex = "SEX_REGEX"
const SuperiorIDFormat = "SUPERIOR_ID_FORMAT"
const AlternativePhone = "ALTERNATIVE_PHONE"
const AlternativePhoneCountryCode = "ALTERNATIVE_PHONE_COUNTRY_CODE"
const AlternativeEmail = "ALTERNATIVE_EMAIL"
const BirthPlace = "BIRTH_PLACE"
const BirthDate = "BIRTH_DATE"
const Occupation = "OCCUPATION"
const SpouseFirstName = "SPOUSE_FIRST_NAME"
const SpouseLastName = "SPOUSE_LAST_NAME"
const SpouseBirthDate = "SPOUSE_BIRTH_DATE"
const AnniversaryDate = "ANNIVERSARY_DATE"
const Latitude = "LATITUDE"
const Longitude = "LONGITUDE"
const PKPStatus = "PKP_STATUS"
const BUMNStatus = "BUMN_STATUS"
const PBFStatus = "PBF_STATUS"
const PBFLicenseNumber = "PBF_LICENSE_NUMBER"
const PBFLicenseEndDate = "PBF_LICENSE_END_DATE"
const PBFTrusteeSipaNumber = "PBF_TRUSTEE_SIPA_NUMBER"
const PBFSipaLicenseEndDate = "PBF_SIPA_LICENSE_END_DATE"
const Brand = "BRAND"
const OwnedStartDate = "OWNED_START_DATE"
const OwnedEndDate = "OWNED_END_DATE"
const Role = "ROLE"
const DataGroup = "DATA_GROUP"
const User = "USER"
const Permission = "PERMISSION"
const DataScope = "DATA_SCOPE"
const Level = "LEVEL"
const Scope = "SCOPE"
const PrincipalProductCode = "PRINCIPAL_PRODUCT_CODE"
const ParentCode = "PARENT_CODE"
const Packaging = "PACKAGING"
const Packaging2 = "PACKAGING_2"
const UOM1 = "UOM_1"
const UOM2 = "UOM_2"
const UOM3 = "UOM_3"
const UOM4 = "UOM_4"
const BarcodeListForUOM1 = "BARCODE_LIST_FOR_UOM_1"
const BarcodeListForUOM2 = "BARCODE_LIST_FOR_UOM_2"
const BarcodeListForUOM3 = "BARCODE_LIST_FOR_UOM_3"
const BarcodeListForUOM4 = "BARCODE_LIST_FOR_UOM_4"
const Conversion1To4 = "CONVERSION_1_TO_4"
const Conversion2To4 = "CONVERSION_2_TO_4"
const Conversion3To4 = "CONVERSION_3_TO_4"
const IsFreeGoodItem = "IS_FREE_GOOD_ITEM"
const IsEmbalanceItem = "IS_EMBALANCE_ITEM"
const IsTax1Applied = "IS_TAX_1_APPLIED"
const IsTax2Applied = "IS_TAX_2_APPLIED"
const IsTax3Applied = "IS_TAX_3_APPLIED"
const IsTaxSubsidized = "IS_TAX_SUBSIDIZED"
const IsNoRegularDiscount = "IS_NO_REGULAR_DISCOUNT"
const MarketLaunchDate = "MARKET_LAUNCH_DATE"
const NIENumber = "NIE_NUMBER"
const NIENumberExpiredDate = "NIE_NUMBER_EXPIRED_DATE"
const ReportColumnHeader1 = "REPORT_COLUMN_HEADER_1"
const ReportColumnHeader2 = "REPORT_COLUMN_HEADER_2"
const ParentID = "PARENT_ID"
const Connector = "CONNECTOR"
const JoinDate = "JOIN_DATE"
const ResignDate = "RESIGN_DATE"
const SuperiorID = "SUPERIOR_ID"
const ElasticKey = "ELASTIC_KEY"
const ShortCode = "SHORT_CODE"
const Name2 = "NAME_2"
const CodeBottle = "CODE_BOTTLE"
const CodeCrate = "CODE_CRATE"
const FarmalkesID = "FARMALKES_ID"
const FarmalkesDesc = "FARMALKES_DESC"
const ServiceMenu = "SERVICE_MENU"
const MenuItem = "MENU_ITEM"
const JobProcess = "JOB_PROCESS"
const JobID = "JOB_ID"
const ClientID = "CLIENT_ID"
const ClientMapping = "CLIENT_MAPPING"
const AuthUserID = "AUTH_USER_ID"
const Cron = "CRON"
const HostID = "HOST_ID"
const HostServer = "HOST_SERVER"
const CronID = "CRON_ID"
const CronHost = "CRON_HOST"
const CronScheduler = "CRON_SCHEDULER"
const HostUrl = "HOST_URL"
const Group = "GROUP"
const UpdatedAtStart = "UPDATED_AT_START"
const UpdatedAtEnd = "UPDATED_AT_END"

// -------------------------------------------- Client Registration ----------------------------------------------------
const CompanyID = "COMPANY_ID"
const BranchID = "BRANCH_ID"
const ClientTypeID = "CLIENT_TYPE_ID"
const ClientName = "CLIENT_NAME"
const ClientSecret = "CLIENT_SECRET"
const ClientSignature = "CLIENT_SIGNATURE"
const SocketUser = "SOCKET_ID"
const SocketPassword = "SOCKET_PASSWORD"

// ----------------------------------------------- Customer List -------------------------------------------------------
const CompanyName = "COMPANY_NAME"
const City = "CITY"
const Implementer = "IMPLEMENTER"
const ImplementationAt = "IMPLEMENTATION_AT"
const Version = "VERSION"
const ExpDate = "EXPIRED_DATE"

// ---------------------------------------------- PKCE Registration ----------------------------------------------------
const ParentClientID = "PARENT_CLIENT_ID"

const CurrentPassword = "CURRENT_PASSWORD"
const NewPassword = "NEW_PASSWORD"
const ConfirmationPassword = "CONFIRMATION_PASSWORD"

// ------------------------------------------- Change Password USER FE -------------------------------------------------
const VerifyPassword = "VERIFY_PASSWORD"
const Locale = "locale"

// ------------------------------------------ Map Import Customer List -------------------------------------------------
const MapCompanyID = "CompanyID"
const MapBranchID = "BranchID"
const MapCompanyName = "CompanyName"
const MapCity = "City"
const MapImplementer = "Implementer"
const MapImplementation = "Implementation"
const MapProduct = "Product"
const MapVersion = "Version"
const MapLicenseType = "LicenseType"
const MapUserAmount = "UserAmount"
const MapExpDate = "ExpDate"

// ------------------------------------------ Customer Group Bundle ----------------------------------------------------
const CustomerGroup = "CUSTOMER_GROUP"
const CustomerGroupName = "CUSTOMER_GROUP_NAME"
const CustomerGroupID = "CUSTOMER_GROUP_ID"

// ---------------------------------------------- Salesman Bundle ------------------------------------------------------
const SalesmanID = "SALESMAN_ID"
const NIKRegex = "NIK_REGEX"
const PhoneRegex = "PHONE_REGEX"

// ------------------------------------------ Customer Category Bundle -------------------------------------------------
const CustomerCategory = "CUSTOMER_CATEGORY"
const CustomerCategoryName = "CUSTOMER_CATEGORY_NAME"
const CustomerCategoryID = "CUSTOMER_CATEGORY_ID"
const ProductGroup = "PRODUCT_GROUP"
const ProductGroupName = "PRODUCT_GROUP_NAME"

// ---------------------------------------------- License Variant ------------------------------------------------------
const LicenseVariant = "LICENSE_VARIANT"
const LicenseVariantName = "LICENSE_VARIANT_NAME"

// ---------------------------------------------- License Type ------------------------------------------------------
const LicenseType = "License Type"
const LicenseTypeConstanta = "LICENSE_TYPE"
const LicenseTypeName = "License Type Name"
const LicenseTypeDesc = "License Type Desc"

// ----------------------------------------------------- Module --------------------------------------------------------
const Module = "MODULE"
const ModuleName = "MODULE_NAME"

// -------------------------------------------------- Component --------------------------------------------------------
const Component = "COMPONENT"
const ComponentName = "COMPONENT_NAME"

// --------------------------------------------------- Product ---------------------------------------------------------
const ProductGroupID = "PRODUCT_GROUP_ID"
const ProductName = "PRODUCT_NAME"
const LicenseVariantID = "LICENSE_VARIANT_ID"
const LicenseTypeID = "LICENSE_TYPE_ID"
const DeploymentMethod = "DEPLOYMENT_METHOD"
const NumberOfUser = "NUMBER_OF_USER"
const ProductDescription = "PRODUCT_DESCRIPTION"
const ComponentID = "COMPONENT_ID"
const ProductComponentID = "PRODUCT_COMPONENT_ID"
const NewClientType = "NEW_CLIENT_TYPE_ID"
const ComponentValue = "COMPONENT_VALUE"
const DeploymentMethodRegex = "DEPLOYMENT_METHOD_REGEX"
const MaxOfflineDays = "MAX_OFFLINE_DAYS"

// --------------------------------------------------- Position --------------------------------------------------------
const Position = "POSITION"
const PositionTitle = "POSITION_TITLE"

// --------------------------------------------------- Customer --------------------------------------------------------
const Customer = "CUSTOMER"
const CustomerName = "CUSTOMER_NAME"
const ParentCustomerID = "PARENT_CUSTOMER_ID"
const CompanyEmail = "COMPANY_EMAIL"
const AlternativeCompanyEmail = "ALTERNATIVE_COMPANY_EMAIL"
const CustomerID = "CUSTOMER_ID"
const MDBPersonTitleID = "MDB_PERSON_TITLE_ID"
const MDBPositionID = "MDB_POSITION_ID"
const MDBPersonProfileID = "MDB_PERSON_PROFILE_ID"
const SiteID = "SITE_ID"
const InstallationNumber = "INSTALLATION_NUMBER"
const UniqueID1 = "UNIQUE_ID_1"
const UniqueID2 = "UNIQUE_ID_2"
const Remark = "REMARK"
const Resource = "RESOURCE"
const ProductValidFrom = "PRODUCT_VALID_FROM"
const ProductValidThru = "PRODUCT_VALID_THRU"
const InstallationDate = "INSTALLATION_DATE"
const InstallationStatus = "INSTALLATION_STATUS"
const InstallationUniqueRegex = "INSTALLATION_UNIQUE_REGEX"
const ActionCode = "ACTION_CODE"
const CustomerSource = "CUSTOMER_SOURCE"
const RefCustomerID = "REF_CUSTOMER_ID"
const CustomerContact = "CUSTOMER_CONTACT"
const LicenseConfig = "License Configuration"
const ProductLicense = "PRODUCT_LICENSE"
const ApplicationDetail = "APPLICATION_DETAIL"
const DistributorOf = "DISTRIBUTOR_OF"
const ProductDetail = "PRODUCT_DETAIL"
const ActionCodeRegex1 = "ACTION_CODE_REGEX_1"
const ActionCodeRegex2 = "ACTION_CODE_REGEX_2"
const CustomerErrorInvalidNPWP = "CUSTOMER_ERROR_NPWP_INVALID"
const CustomerInstallation = "CUSTOMER_INSTALLATION"
const CustomerSiteRegex = "SITE_REGEX"
const CustomerInstallationRegex = "INSTALLATION_REGEX"

// --------------------------------------------------- License Config --------------------------------------------------
const InstallationID = "INSTALLATION_ID"
const Installation = "INSTALLATION"
const NewInstallationID = "NEW_INSTALLATION_ID"
const HWID = "HWID"
const AllowActivation = "ALLOW_ACTIVATION"

// --------------------------------------------------- Product License  ------------------------------------------------
const ProductLicenseID = "PRODUCT_LICENSE_ID"
const LicenseStatus = "license status"

// --------------------------------------------------- User License  ---------------------------------------------------
const UserLicenseID = "USER_LICENSE_ID"
const ClientType = "CLIENT_TYPE"
const UserLicense = "user license"
const UserID = "USER_ID"

// -------------------------------------------------- Activation License -----------------------------------------------
const ActivationLicenseGetLicenseConfigError = "GET_LICENSE_CONFIG_ERROR"
const ActivationLicenseGetJSONFileError = "GET_JSON_FILE_ERROR"
const ActivationLicenseGetProductLicenseError = "GET_PRODUCT_LICENSE_ERROR"
const ActivationLicenseEncryptLicenseError = "ENCRYPT_LICENSE_ERROR"
const ActivationLicenseDecryptLicenseError = "DECRYPT_LICENSE_ERROR"
const ActivationLicenseCreateProductLicenseError = "CREATE_PRODUCT_LICENSE_ERROR"
const ActivationLicenseCreateUserLicenseError = "CREATE_USER_LICENSE_ERROR"
const ActivationLicenseProductLicenseExpiredError = "EXPIRED_PRODUCT_LICENSE_ERROR"

// ---------------------------------------------------- Is Concurrent --------------------------------------------------
const IsConcurrent = "Is Concurrent"

// ----------------------------------------------- Registration Client Mapping -----------------------------------------
const ClientMappingClientID = "CLIENT_ID_CLIENT_MAPPING"
const ClientMappingAuthUserID = "AUTH_USER_ID_CLIENT_MAPPING"
const ClientMappingUserID = "USER_ID_CLIENT_MAPPING"
const ClientMappingPassword = "PASSWORD_CLIENT_MAPPING"
const ClientMappingAndroidID = "ANDROID_ID_CLIENT_MAPPING"
const ClientMappingRegDate = "REG_DATE_CLIENT_MAPPING"
const SalesmanCategory = "SALESMAN_CATEGORY"
const SignatureKey = "SIGNATURE_KEY"
const ClientMappingParentClientID = "PARENT_CLIENT_ID_CLIENT_MAPPING"
const ClientMappingClientAlias = "CLIENT_ALIAS_CLIENT_MAPPING"

// ----------------------------------------------- User Registration Detail --------------------------------------------
const UserRegistrationDetailID = "USER_REGISTRATION_DETAIL_ID"

// ----------------------------------------------- User Registration ---------------------------------------------------
const UserRegistrationAdmin = "USER_REGISTRATION"
const UserRegistrationID = "USER_REGISTRATION_ID"
const UserAdmin = "USER_ADMIN"
const UserAuth = "USER_AUTH"
const PasswordAdmin = "PASSWORD_ADMIN"
const BranchName = "BRANCH_NAME"

// ----------------------------------------------- Activation License Nexmile ------------------------------------------
const UserRegistrationDetailIDName = "USER_REGISTRATION_DETAIL_ID"
const UserRegistrationDetailName = "USER_REGISTRATION_DETAIL"
const ActivationUserNexmileErrorUserLicense = "ACTIVATION_USER_NEXMILE_ERROR_USER_LICENSE"

// -------------------------------------------------------- Role -------------------------------------------------------
const RolePermissionErrorLevelConstanta = "ERROR_LEVEL_PERMISSION"

// ---------------------------------------------- Nexmile Parameter ----------------------------------------------------
const ParameterID = "PARAMETER_ID"
const ParameterValue = "PARAMETER_VALUE"
const AndroidID = "ANDROID_ID"

// ---------------------------------------------- Client Mapping -------------------------------------------------------
const ClientAlias = "CLIENT_ALIAS"
const DetailClient = "DETAIL_CLIENT"
const PKCEClientMapping = "PKCE_CLIENT_MAPPING"

// ---------------------------------------------- License Generator ----------------------------------------------------
const HardwareID = "HARDWARE_ID"
const HardwareIDInternal = "HARDWARE_ID_INTERNAL"

// ---------------------------------------------- User Verification ----------------------------------------------------
const UserVerification = "USER_VERIFICATION"
const OTP = "OTP"
const InvalidOTPRequestCombination = "INVALID_REQUEST_COMBINATION_VERIFYING_NEXMILE"
const InvalidVerifyingRequetCombination = "VERIFYING_USER_MANDATORY_EMAIL_PHONE"

// ------------------------------------------------ User ---------------------------------------------------------------
const StatusUserRegex = "STATUS_USER_REGEX"

// ----------------------------------------------- Resend OTP ----------------------------------------------------------
const ResendOTPService = "RESEND_OTP_SERVICE"
const ResendOTPEmailPhoneRule = "RESEND_OTP_EMAIL_PHONE_RULE"
const EmailPhone = "EMAIL_PHONE"
const InvalidRequestEmailPhone = "INVALID_REQUEST_EMAIL_PHONE"
const FailedRequestClientCredential = "FAILED_REQUEST_CLIENT_CREDENTIAL"
const FailedRequestUserNotFound = "FAILED_REQUEST_USER_NOT_FOUND"
const FailedRequestPhoneNotFound = "FAILED_REQUEST_PHONE_NOT_FOUND"
const FailedVerificationProcess = "FAILED_VERIFICATION_PROCESS"
const CountryCode = "COUNTRY_CODE"
const UserActiveStatus = "USER_ACTIVE"

// ------------------------------ Constanta For Set Status User --------------------------------------------------------
const StatusActiveString = "ACTIVE_SIGN"
const StatusNonActiveString = "NOT_ACTIVE_SIGN"
const StatusNotVerifiedYet = "NOT_VERIFIED_YET"

const WrongActivationCode = "WRONG_ACTIVATION_CODE"
const WrongEmailData = "WRONG_EMAIL_DATA"
const WrongPhoneData = "WRONG_PHONE_DATA"
const ExpiredActivationCode = "EXPIRED_ACTIVATION_CODE"
const WrongFormatPhone = "WRONG_FORMAT_PHONE"
const WrongOTPCode = "WRONG_OTP_CODE"

// ------------------------------------------------ Error Rule Name ----------------------------------------------------

const NeedMoreThan = "NEED_MORE_THAN"
const NeedLessThan = "NEED_LESS_THAN"
const OnlyNumeric = "ONLY_NUMERIC"
const MismatchRegionalData = "MISMATCH_REGIONAL_MDB_DATA"
const MaxValueProductValidFrom = "MAXIMUM_VALUE_PRODUCT_VALID_FROM"
const MaxValueProductValidThru = "MAXIMUM_VALUE_PRODUCT_VALID_THRU"

// ------------------------------------------------ Remark Name ----------------------------------------------------
const ActionClientTypeRemarkName = "Action Client Type"
const InvalidRemarkRequestCombination = "INVALID_REQUEST_COMBINATION_VERIFYING_NEXMILE"

// ------------------------------------------ WhiteList Device ---------------------------------------------------------
const Device = "DEVICE"
const DescriptionDevice = "DESCRIPTION"

// ------------------------------------------------ Department ---------------------------------------------------------
const DepartmentConstanta = "DEPARTMENT"
const DepartmentId = "DEPARTMENT_ID"

// -------------------------------------------------- Employee ---------------------------------------------------------
const EmployeeConstanta = "EMPLOYEE"
const RedmineId = "REDMINE_ID"
const EmployeeID = "EMPLOYEE_ID"
const Religion = "RELIGION"
const DateOut = "DATE_OUT"
const DateJoin = "DATE_JOIN"
const Marital = "MARITAL"
const Nationality = "NATIONALITY"
const Bpjs = "BPJS"
const BpjsTk = "BPJS_TK"
const Grade = "GRADE"
const Member = "MEMBER"
const Education = "EDUCATION"
const MothersMaiden = "MOTHERS_MAIDEN"
const NumbersDependants = "NUMBERS_DEPENDANTS"
const TaxMethod = "TAX_METHOD"
const AddressTax = "ADDRESS_TAX"

// ------------------------------------------------------ Enum ---------------------------------------------------------
const EnumConstanta = "ENUM"

// --------------------------------------------------- Backlog ---------------------------------------------------------
const BacklogConstanta = "BACKLOG"
const DepartmentName = "DEPARTMENT_NAME"
const Department = "DEPARTMENT"
const DepartmentCode = "DEPARTMENT_CODE"
const Layer1 = "LAYER_1"
const Layer2 = "LAYER_2"
const Layer3 = "LAYER_3"
const Layer4 = "LAYER_4"
const Layer5 = "LAYER_5"
const RedmineNumber = "REDMINE_NUMBER"
const Feature = "FEATURE"
const Subject = "SUBJECT"
const ReferenceTicket = "REFERENCE_TICKET"
const Sprint = "SPRINT"
const SprintName = "SPRINT_NAME"
const PicId = "PIC_ID"
const Mandays = "MANDAYS"
const MandaysDone = "MANDAYS_DONE"
const MandaysRate = "Mandays Rate"
const MandaysRateAutomation = "Mandays Rate Automation"
const MandaysRateManual = "Mandays Rate Manual"
const FlowChanged = "FLOW_CHANGED"
const AdditionalData = "ADDITIONAL_DATA"
const Note = "NOTE"
const Url = "URL"
const Tracker = "TRACKER"
const BacklogRule1 = "BACKLOG_RULE_1"

// --------------------------------------------------- Report ----------------------------------------------------------
const ReportConstanta = "REPORT"
const SprintStart = "SPRINT_START"
const SprintEnd = "SPRINT_END"
const SprintRule1 = "SPRINT_RULE_1"
const SprintRule2 = "SPRINT_RULE_2"
const SprintRule3 = "SPRINT_RULE_3"
const DepartmentRule1 = "DEPARTMENT_RULE_1"

// ---------------------------------------------- Standar Manhour ------------------------------------------------------
const StandarManhour = "STANDAR_MANHOUR"
const Case = "CASE"
const Manhour = "MANHOUR"
const ManhourRule1 = "MANHOUR_RULE_1"

// -------------------------------------------------- Migration --------------------------------------------------------
const Migration = "MIGRATION"

// ---------------------------------------------- Employee Contract ----------------------------------------------------
const EmployeeContract = "EMPLOYEE_CONTRACT"
const ContractNo = "CONTRACT_NO"
const Information = "INFORMATION"
const FromDate = "FROM_DATE"
const ThruDate = "THRU_DATE"

// ----------------------------------------------- Status Constanta ----------------------------------------------------
const LeaveStatus = "LEAVE"
const SickStatus = "SICK"
const PermitStatus = "PERMIT"
